version: "3"

services:
  todoweb:
    build: .
    command: bash -c "uvicorn application:app --host 0.0.0.0 --port 8000 --reload"
    image: todoimg
    volumes:
      - .:/todo-app
    ports:
      - 8000:8000
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017